### ISSUE TITLE
Starting Ammo not being applied + Onplayerhurting error present. 

### ISSUE THREAD

**Issue by Purriku** [Exiled-Team/Common-Utils#82] opened 2021-12-01 22:13 UTC
**Describe the bug**
- starting ammo configs not applied to classes upon spawn
- error for onplayerhurting present in console whenever someone dies or disconnects

**To Reproduce**

-CU error-
1. spawn in
2. disconnect or die
3. console prints error
--------------------------
-Starting Inv.-
1. Spawn in as a class with custom ammo amount
2. Ammo not added to inventory
3. Cringe

**Expected behavior**
- No errors 
- Starting ammo inventories applied correctly. 

**Server logs**

- debug console printout of starting inventories - https://pastebin.com/MNQNx0j2

- full cu config - https://pastebin.com/WCa1yVzr

- LAlog - https://pastebin.com/j6qV4MBV

- Console Error Printout - https://pastebin.com/JiTWGjMj

- Full Plugin List - https://pastebin.com/buCgjjga

**Comment by Purriku** [comment] 2021-12-01 22:16
using 5.0.1

**Comment by joker-119** [comment] 2021-12-01 22:17
The hurting error was fixed in 5.0.2, i'll look into ammo shortly.

**Comment by Purriku** [comment] 2021-12-01 22:18
> The hurting error was fixed in 5.0.2, i'll look into ammo shortly.

Sounds good. I will update and reply if anything else is noticed

I did notice in debug it has a () after ammo amount. I wonder if that is %chance of spawning with item possibly?

**Comment by Purriku** [comment] 2021-12-01 22:35
Now when player spawns in i see this every now and then

----------------------------

[2021-12-01 14:31:27.643 -08:00] [ERROR] [Exiled.Events] Method "OnChangingRole" of the class "Common_Utilities.EventHandlers.PlayerHandlers" caused an exception when handling the event "Exiled.Events.Events+CustomEventHandler`1[[Exiled.Events.EventArgs.ChangingRoleEventArgs, Exiled.Events, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null]]"
[2021-12-01 14:31:27.656 -08:00] [ERROR] [Exiled.Events] System.NullReferenceException: Object reference not set to an instance of an object
                                   at Common_Utilities.EventHandlers.PlayerHandlers.OnChangingRole (Exiled.Events.EventArgs.ChangingRoleEventArgs ev) [0x00086] in <b1249147721643849693a028614ad1b1>:0
                                   at Exiled.Events.Extensions.Event.InvokeSafely[T] (Exiled.Events.Events+CustomEventHandler`1[TEventArgs] ev, T arg) [0x00024] in <789cd91facaf4915a4bd60f8d2062034>:0

**Comment by joker-119** [comment] 2021-12-01 22:55
The only way that can happen is if player auth on the server broke and player objects aren't being created

**Comment by Purriku** [comment] 2021-12-03 00:16
dont think making a new issue for this is warranted. noticed 5.0.4 prints out in console as 5.0.3. Ammo still has the same issue (im guessing you havent gotten to it yet, no worries if so.)

**Comment by Firexik** [comment] 2021-12-03 16:04
> dont think making a new issue for this is warranted. noticed 5.0.4 prints out in console as 5.0.3. Ammo still has the same issue (im guessing you havent gotten to it yet, no worries if so.)

I got the same issue here, I hope it will get fixed soon.

**Comment by EsserGaming** [comment] 2021-12-05 04:28
I can confirm that this error is present!

**Comment by Purriku** [comment] 2021-12-08 07:30
> > dont think making a new issue for this is warranted. noticed 5.0.4 prints out in console as 5.0.3. Ammo still has the same issue (im guessing you havent gotten to it yet, no worries if so.)
> 
> I got the same ammo issue here, I hope it will get fixed soon.

when I look at the debug I notice the ammo amount has () after the amount. Similar to how %chance for items is. I wonder if that () is %chance 
                                                                                                                                                                                   
[2021-12-01 12:33:07.226 -08:00] [DEBUG] [Common_Utilities] Ammo Config: NtfSpecialist - Ammo556x45 500 () <-- possibly %chance??
[2021-12-01 12:33:07.237 -08:00] [DEBUG] [Common_Utilities] Inventory Config: NtfSergeant - Slot1: GunE11SR (100) <-- %chance

**Comment by VideoGamerRUS** [comment] 2021-12-09 12:34
Yes, the ammo is giving incorrectly

**Comment by Laronzis** [comment] 2021-12-16 20:21
still don't works on 5.0.4

**Comment by Firexik** [comment] 2021-12-28 16:19
still not fixed, rip.. :/

**Comment by joker-119** [comment] 2021-12-28 19:13
anger...  It works fine for me everytime I test it..

**Comment by Firexik** [comment] 2021-12-28 21:44
Idk then, there is multiple people that have issues with it...perhaps, I could send mine logs too for you to investigate?

**Comment by Purriku** [comment] 2021-12-29 17:57
> anger... It works fine for me everytime I test it..

thats no bueno. i havent changed config or version since it was updated and still same issue. I will turn off some plugins and see if its a conflict with one 

ill report back if i find anything

**Comment by Purriku** [comment] 2021-12-29 18:17
turned all plugins off. version cu 5.0.4 (says 5.0.3 in console)
la log ----> https://pastebin.com/BBxVuqf
photo evidence --> ![private](https://user-images.githubusercontent.com/87593087/147691750-39cfa058-86f2-4a98-99de-dc2762975486.png)
g

**Comment by joker-119** [comment] 2021-12-29 19:21
Both the issues listed here should be fixed in 5.0.5, I'm unable to reproduce either in that version.

**Closed by joker-119** 2021-12-29 19:21 UTC
Labels: bug
